name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Replace '3.x' with your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest  # Ensure 'pytest' is included in requirements.txt

      - name: Lint code
        run: |
          pip install flake8
          flake8 .

  success:
    runs-on: ubuntu-latest
    steps:
      - name: Success
        run: echo 'Build completed successfully!'

  failure:
    runs-on: ubuntu-latest
    steps:
      - name: Failure
        run: echo 'Build failed!'
